### ISSUE TITLE
Replace gen_fsm with gen_statem

### ISSUE THREAD

**Issue by benbro** [RoadRunnr/dtlsex#12]
gen_fsm in [dtlsex_connection](https://github.com/RoadRunnr/dtlsex/blob/master/src/dtlsex_connection.erl) is deprecated in OTP 21. Can we replace it with [gen_statem](http://erlang.org/doc/man/gen_statem.html)?

**Comment by RoadRunnr** [comment]
OTP 21 does include official DTLS support. Sure, the API is different, but there also many general improvements in the TLS stack.

I therefore don't see any future for this project. It was always intended as a interim solution till DTLS support in the official OTP release was ready.

If you are missing anything in the upstream DTLS implementation or if you have issues with their API which you prevent you from using it, I would highly encourage you and appreciate it if you raise this on the erlang-question mailing list. I also have a project that needs to be migrated from DTLSex to OTP 21 and would love to share experiences on that.

**Comment by benbro** [comment]
I need DTLS-SRTP which means the same UDP connection will be used for DTLS, STUN and RTP.
From your [question](http://erlang.org/pipermail/erlang-questions/2018-January/094581.html) on the mailing list I got the impression that the DTLS implementation in erlang doesn't support this use case.
I'll check again. Thanks.
