### ISSUE TITLE
Client example

### ISSUE THREAD

**Issue by benbro** [RoadRunnr/dtlsex#3]
I'm trying to use dtlsex as a client.

dtlsex_handshake expects ssl version like {3, 4} but dtls 1.2 has a version of { 254, 253 }
https://github.com/RoadRunnr/dtlsex/blob/5a3a55a085e379ee0e95c9c09932f73f69391e25/src/dtlsex_handshake.erl#L1521

```
connect(Address, Port, Key, Cert) ->
  {ok, Socket} = gen_udp:open(0, [binary, {active, true}, {recbuf, 8192}]),
  ok = gen_udp:connect(Socket, Address, Port),
  Ciphers = dtlsex:cipher_suites(all),
  Options = [{versions, ['dtlsv1.2', dtlsv1]},
                   {cb_info, dtlsex_udp},
                   {active, false},
                   {ciphers, Ciphers},
                   {certfile,Cert},
                   {keyfile, Key}],
  dtlsex:connect(Socket, Options).
```

error:

```
SSL: certify: src/dtlsex_handshake.erl:1538:Fatal error: handshake failure
```

**Comment by RoadRunnr** [comment]
@benbro you need to add `{protocol, dtls}` to your options.

I have uploaded my test dtls client here: https://gist.github.com/RoadRunnr/27179905a341a51a0f53

**Comment by benbro** [comment]
I've added {protocol, dtls}.

When using  {versions, ['dtlsv1.2']} I'm getting the same error:

```
SSL: certify: src/dtlsex_handshake.erl:1538:Fatal error: handshake failure
```

When using {versions, [dtlsv1]}, I'm getting the following error in Firefox as a dtls server:

```
SSL: cipher: src/dtlsex_connection.erl:2263:Fatal error: decrypt error
```

And the following error when Chrome is the dtls server:

```
dtlsex_udp info: {ssl_error,{sslsocket,{dtlsex_udp,#Port<0.2527>},<0.224.0>},
                            {tls_alert,"record overflow"}}
```

``` erlang
connect(Address, Port, Key, Cert) ->
  {ok, Socket} = gen_udp:open(0, [binary, {active, true}, {recbuf, 8192}]),
  ok = gen_udp:connect(Socket, Address, Port),
  Ciphers = dtlsex:cipher_suites(all),
  Options = [{ssl_imp,new},
                   {verify, 0},
                   {active, false},
                   {ciphers, Ciphers},
                   {certfile,Cert},
                   {keyfile, Key},
                   {protocol, dtls},
                   {versions, [dtlsv1]},
                   {cb_info, {dtlsex_udp, dtlsex_udp, udp_close, udp_error}}],
  dtlsex:connect(Socket, Options).
```

**Comment by RoadRunnr** [comment]
I'm currently at netdev, so responses are a bit slow...

@benbro the error message itself doesn't reveal much. Could you provide instruction on how to use Firefox and Chrome as DTLS servers? (don't really have the time to dig into that myself right now)

Also, a pcap trace might give some addition clues, could you provide one?

**Comment by benbro** [comment]
I'll try to use dtlex for both client and server first.
Than I'll try to connect it to Firefox or Chrome acting as DTLS server and capture a pcap trace.
Thanks

**Comment by RoadRunnr** [comment]
@benbro I just discovered a problem with ECDH keys and Erlang R18. A fix is already on master. Could you retry with the current head to make sure this is not the error you are seeing, please.

**Comment by achowdhury918** [comment]
Hi RoadRunnr,
2 days ago, you wrote -"I'll try to use dtlsex for both client and server first.". Did you get chance to do that? I need to use it for server. Is dtlsex tested for server? Do you think at this point this is usable/reliable? Please, let us know. 
Thanks.

**Comment by achowdhury918** [comment]
Hi BenBro,
2 days ago, you wrote -"I'll try to use dtlsex for both client and server first.". Did you get chance to do that? I need to use it for server. Is dtlsex tested for server? Do you think at this point this is usable/reliable? Please, let us know. 
Thanks.

**Comment by RoadRunnr** [comment]
@achowdhury918 we are using DTLSex on production servers under R17 and now also under R18, clients are using OpenSSL. Currently, I'm also evaluating a client that is using WolfSSL without any problems so far.

There was a problem with ECDH under R18, but that has been fixed in last commits.

I have no idea how to use Chrome or Firefox as DTLS client or server (as BenBro did). I assume that this is related to webrtc or something similar.

**Comment by achowdhury918** [comment]
Hi RoadRunnr,
Thanks a lot for your reply.
Regards.

**Comment by achowdhury918** [comment]
Hi RoadRunnr,
You have example client in the following location:
https://gist.github.com/RoadRunnr/27179905a341a51a0f53
Could you please give me location of your example server? Thanks in advance for your help.

**Comment by achowdhury918** [comment]
@RoadRunnr , could you please reply? As there is no documentation on it at all. I need your help. Your little help can save my days or weeks.
@benbro, if you have the answer, then you can help me too. 
Any help regarding this will be highly appreciated.
Thanks.

**Comment by benbro** [comment]
@RoadRunnr tested again with master.
I'm getting an error:

``` erlang
{badmatch,
        {error,{options,{socket_options,[{active,false},{protocol,dtls}]}}}}
```

``` erlang
Ciphers = dtlsex:cipher_suites(all),
Options = [{ssl_imp,new},
                 {verify, verify_none},
                 {active, false},
                 {ciphers, Ciphers},
                 {certfile,Cert},
                 {keyfile, Key},
                 {protocol, dtls},
                 {versions, ['dtlsv1.2',dtlsv1]},
                 {cb_info, {dtlsex_udp, dtlsex_udp, udp_close, udp_error}}],
{ok, Socket} = dtlsex:connect(Host, Port, Options).
```

**Comment by RoadRunnr** [comment]
The protocol options was introduced with newer version of the SSL application and is not a valid option for this version. Setting the cb_info is enough.

**Comment by benbro** [comment]
After removing {protocol, dtls} I'm getting an error about ssl not started, although application:which_applications() shows that the ssl application is started.

``` erlang
{{badmatch,{error,ssl_not_started}},
```

I'm using OTP 17.1 but can test in other versions if needed.

**Comment by RoadRunnr** [comment]
you need to start dtlsex as well

**Comment by benbro** [comment]
Thanks, I'm making some progress. Now I'm getting:
`Fatal error: handshake failure`

There are several places where the major and minor versions are expected to be ~3.
Is this correct because the major and minor versions of dtls are {254,255} for dtls-1.0 and {254,253} for dtls-1.2.
https://github.com/RoadRunnr/dtlsex/blob/master/src/dtlsex_handshake.erl#L1774

**Comment by RoadRunnr** [comment]
That particular place is about the HasSign extension and is only used in DTLS-1.2.

You are right that I would not work for DTLS-1.2. I'm currently using it in DTLS-1.0 mode only, So it could be that DTLS-1.2 will run into some problems.

However, not sending the HashSign extension in DTLS-1.2 should be ok, the other side should fall back to some defaults.

The more likely cause for the handshake failure is the DTLS Hello Verification request. Some OpenSSL versions are using invalid sequence numbers in the second Client Hello.

**Comment by benbro** [comment]
'dtlsv1.2' gives me:
SSL: certify: src/dtlsex_handshake.erl:1574:Fatal error: handshake failure

dtlsv1 gives me:

``` erlang
info: {ssl_error,{sslsocket,{dtlsex_udp,#Port<0.2523>},<0.220.0>},
                         {tls_alert,"record overflow"}}
```

**Comment by RoadRunnr** [comment]
never seen "record overflow" before. Could you provide some pcap's of the handshake?

**Comment by benbro** [comment]
I had another protocol multiplexed on the same port, that's why I got "record overflow".
Thanks.

dtlsex_handshake is missing a clause for DTLS 1 and 1.2 versions. It only handles version {3, _}.
That breaks dtlsex:prf/5.
https://github.com/RoadRunnr/dtlsex/blob/master/src/dtlsex_handshake.erl#L804
Maybe this is missing?

``` erlang
prf({254, _}, Secret, Label, Seed, WantedLength) ->
    {ok, dtlsex_tls1:prf(?MD5SHA, Secret, Label, Seed, WantedLength)};
```

**Comment by RoadRunnr** [comment]
Multiplex DTLS and other protocols over the same UDP socket is best done by creating a copy of dtlsex_udp.erl and handling the multiplexing/demultiplexing there.

**Comment by benbro** [comment]
I don't think it's possible to multiplex with a custom callback module.
dtlx_connection calls Transport:handle_ssl_info(Socket, Msg) but it's not currently possible to return something like 'ignore' or 'pass
https://github.com/RoadRunnr/dtlsex/blob/master/src/dtlsex_connection.erl#L1238

``` erlang
handle_info(Msg, StateName,
            #state{socket = Socket, transport_cb = Transport} = State) ->
    case Transport:handle_ssl_info(Socket, Msg) of
    {next, NextMsg} ->
        handle_info(NextMsg, StateName, State);
    ignore ->
        {next_state, StateName, State, get_timeout(State)};
    _ ->
        Report = io_lib:format("SSL: Got unexpected info: ~p ~n", [Msg]),
        error_logger:info_report(Report),
        {next_state, StateName, State, get_timeout(State)}
    end.
```

**Comment by RoadRunnr** [comment]
No, it does work, for an example (minus some supporting code) see here:

https://gist.github.com/RoadRunnr/f5388519efd4babe9f09

This does multiplex encrypted and unencrypted CAPWAP traffic over the same UDP socket.

**Comment by benbro** [comment]
I think that in your example you multiplex on a DTLS server.
I need to multiplex on a DTLS client.

dtlsex_connection receive the UDP packet and pass it to the callback module.
https://github.com/RoadRunnr/dtlsex/blob/master/src/dtlsex_connection.erl#L1238

The callback module can handle the packet but it has no way to tell dtlsex_connection to ignore the packet:
https://github.com/RoadRunnr/dtlsex/blob/master/src/dtlsex_udp.erl#L106

**Comment by benbro** [comment]
I'm closing this issue because it gets long.
I'll open a new issue about demultiplexing on a dtlsex client.
