### ISSUE TITLE
Getting error in dtlsex:recv()

### ISSUE THREAD

**Issue by achowdhury918** [RoadRunnr/dtlsex#4]
Hi,
I am getting following error 

=ERROR REPORT==== 7-Mar-2016::00:50:27 ===
Error in process <0.35.0> with exit value:
{function_clause,[{dtlsex,recv,
                          [#Port<0.773>,5,infinity],
                          [{file,"src/dtlsex.erl"},{line,286}]},
                  {server,loop,1,[{file,"src/server.erl"},{line,31}]}]}

Here is the complete console log:
ubuntu@ip-172-31-0-227:~/dtlsex/ebin$ erl
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V7.2  (abort with ^G)
1> server:start().
<0.35.0>
Result1: {error,{already_started,ssl}}.
server opened socket:#Port<0.773>
Server connected. Result : {error,ssl_not_started}
2>
=ERROR REPORT==== 7-Mar-2016::00:50:27 ===
Error in process <0.35.0> with exit value:
{function_clause,[{dtlsex,recv,
                          [#Port<0.773>,5,infinity],
                          [{file,"src/dtlsex.erl"},{line,286}]},
                  {server,loop,1,[{file,"src/server.erl"},{line,31}]}]}

Here is my program (simple client server program which uses DTLS):

-module(server).
-export([start/0, client/1]).

start() ->
    spawn(fun() -> server(5685) end).

server(Port) ->
    [application:start(X) || X <- [crypto, asn1, public_key, ssl]],
    Result1 = ssl:start(),
    io:format("Result1: ~p. ~n",[Result1]),
    {ok, Socket} = gen_udp:open(Port, [binary, {active, false}]),
    io:format("server opened socket:~p~n",[Socket]),
    ok = gen_udp:connect(Socket, "localhost", Port),
    Ciphers = dtlsex:cipher_suites(all),
    Cert =  "/usr/lib/erlang/lib/ssl-7.2/examples/certs/etc/server/cert.pm",
    Key = "/usr/lib/erlang/lib/ssl-7.2/examples/certs/etc/server/key.pm",
    Options = [{ssl_imp,new},
               {verify, 0},
               {ciphers, Ciphers},
               {certfile,Cert},
               {keyfile, Key},
               {protocol, dtls},
               {versions, [dtlsv1]},
               {cb_info, {dtlsex_udp, dtlsex_udp, udp_close, udp_error}}],
    Result = dtlsex:connect(Socket, Options),
    io:format("Server connected. Result : ~p~n",[Result]), 
    loop(Socket).

loop(Socket) ->
    inet:setopts(Socket, [{active, once}]),
    Value = dtlsex:recv(Socket,5),
    io:format("Server got Value: ~p. ~n",[Value]), 
    Result = dtlsex:send(Socket,Value),
    io:format("Server sent Result: ~p. ~n",[Result]), 
    loop(Socket).

client(N) ->
    [application:start(X) || X <- [crypto, asn1, public_key, ssl]],
    Result3=ssl:start(),
    io:format("Result3: ~p. ~n",[Result3]),
    {ok, Socket} = gen_udp:open(0, [binary, {active, true}, {recbuf, 8192}]),
    io:format("client opened socket=~p~n",[Socket]),
    ok = gen_udp:connect(Socket, "localhost", 5685),
    io:format("After gen_udp:connect ~n"),
    Ciphers = dtlsex:cipher_suites(all),
    Cert =  "/usr/lib/erlang/lib/ssl-7.2/examples/certs/etc/client/cert.pm",
    Key = "/usr/lib/erlang/lib/ssl-7.2/examples/certs/etc/client/key.pm",
    Options = [{ssl_imp,new},
               {verify, 0},
               {active, false},
               {ciphers, Ciphers},
               {certfile,Cert},
               {keyfile, Key},
               {protocol, dtls},
               {versions, [dtlsv1]},
               {cb_info, {dtlsex_udp, dtlsex_udp, udp_close, udp_error}}],
    Result = dtlsex:connect(Socket, Options),
    io:format("After dtlsex:connect. Result: ~p ~n",[Result]),
    Result2 = dtlsex:send(Socket,N),
    io:format("After dtlsex:send. Result2: ~p ~n",[Result2]),
    Value = dtlsex:recv(Socket,5),
    io:format("After dtlsex:recv Value: ~p ~n",[Value]),
    dtlsex:close(Socket),
    Value.  

Why I am getting that error? Am I doing something wrong? Any help regarding this will be highly appreciated.

Thanks.

**Comment by RoadRunnr** [comment]
the **ex** in the name stands for experimental. DTLs is now part of OTP and any project using this version needs to migrate to that.

Consider this project obsolete, abandoned and unsupported.
