### ISSUE TITLE
Packet loss and reordering during handshake

### ISSUE THREAD

**Issue by benbro** [RoadRunnr/dtlsex#7]
In your PR you state that packet loss and packet reordering during handshake are missing.
Does it mean that the handshake will fail in this situation?

Using a different DTLS library for several months, I see that reordered and dropped packets during the handshake are not rare enough to ignore in my case.

**Comment by RoadRunnr** [comment]
DTLSex can deal with packet loss and packet reordering.

 The PR is for R18/R19 and the resend logic from this implementation does not longer fit easily with the new code structure. I want to get the core DTLS support merged first and then add additional things incrementally. Last time I send a complete PR, it was chopped to pieces and I had basically had to redo everything almost from scratch. So, this time a try a more incremental approach.

**Comment by benbro** [comment]
I'll force packet loss and packet reordering and test it.

Thanks
