### ISSUE TITLE
Compilation warnings in R19

### ISSUE THREAD

**Issue by benbro** [RoadRunnr/dtlsex#8]
I'm getting the following warnings when compiling with R19.
1. Is it a problem that size/1 is undefined?
2. Replacing crypto:strong_rand_bytes/1 is easy.
3. Can we replace erlang:now() with erlang:system_time(milli_seconds) or does it need monotonic timestamp?

```
src/dtlsex_session_cache.erl:23: Warning: undefined callback function size/1 (behaviour 'ssl_session_cache_api')
src/dtlsex_record.erl:822: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/dtlsex.erl:568: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/dtlsex_manager.erl:444: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
src/dtlsex_connection.erl:3389: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
```

**Comment by benbro** [comment]
https://github.com/RoadRunnr/dtlsex/pull/11 replaces crypto:rand_bytes/1

**Comment by RoadRunnr** [comment]
the **ex** in the name stands for experimental. DTLs is now part of OTP and any project using this version needs to migrate to that.

Consider this project obsolete, abandoned and unsupported.
